// Copyright (c) 2014-2017 Coin Sciences Ltd
// Copyright (c) 2017b Float Coin Developers

#ifndef FLOATCHAINPARAMLIST_H
#define FLOATCHAINPARAMLIST_H

static const FC_OneFloatchainParam FloatchainParamArray[] =
{
    { "chainprotocol"                          , "chain-protocol"                          ,
                   FC_PRM_STRING  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_SPECIAL , 16,         0,          0,         0, 0.0, 10001, 0, "-FC-chainprotocol",
                   "chaindescription","Basic chain parameters",
                   "Chain protocol: floatchain (permissions, native assets) or bitcoin"},
    { "chaindescription"                       , "chain-description"                       ,
                   FC_PRM_STRING  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_SPECIAL ,256,         0,          0,         0, 0.0, 10001, 0, "-FC-chaindescription",
                   "rootstreamname","",
                   "Chain description, embedded in genesis block coinbase, max 256 chars."},
    { "rootstreamname"                       , "root-stream-name"                       ,
                   FC_PRM_STRING  | FC_PRM_USER | FC_PRM_CLONE  | FC_PRM_SPECIAL,256,         0,          0,         0, 0.0, 10006, 0, "-FC-rootstreamname",
                   "rootstreamopen","",
                   "Root stream name, blank means no root stream."},
    { "rootstreamopen"                       , "root-stream-open"                       ,
                   FC_PRM_BOOLEAN  | FC_PRM_USER | FC_PRM_CLONE                 , -1  ,       1,          0,         0, 0.0, 10006, 0, "-FC-rootstreamopen",
                   "chainistestnet","",
                   "Allow anyone to publish in root stream"},
    { "chainistestnet"                         , "chain-is-testnet"                   ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-chainistestnet",
                   "targetblocktime","",
                   "Content of the 'testnet' field of API responses, for compatibility."},
    { "targetblocktime"                        , "target-block-time"                    ,
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,        15,         2,     86400, 0.0, 10001, 0, "-FC-targetblocktime",
                   "maximumblocksize","",
                   "Target time between blocks (transaction confirmation delay), seconds."},
    { "maximumblocksize"                       , "maximum-block-size"               , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,   8388608,       1000,1000000000, 0.0, 10001, 0, "-FC-maximumblocksize",
                   "defaultnetworkport","",
                   "Maximum block size in bytes."},
    { "defaultnetworkport"                , "default-network-port"              ,
                   FC_PRM_UINT32  | FC_PRM_GENERATED | FC_PRM_CLONE                  , -1, FC_DEFAULT_NETWORK_PORT,       1024,     65535, 0.0, 10001, 0, "-FC-defaultnetworkport",
                   "defaultrpcport","",
                   "Default TCP/IP port for peer-to-peer connection with other nodes."},
    { "defaultrpcport"                    , "default-rpc-port"                  ,
                   FC_PRM_UINT32  | FC_PRM_GENERATED | FC_PRM_CLONE | FC_PRM_MINIMAL , -1, FC_DEFAULT_RPC_PORT,       1024,     65535, 0.0, 10001, 0, "-FC-defaultrpcport",
                   "anyonecanconnect","",
                   "Default TCP/IP port for incoming JSON-RPC API requests."},
                   
    { "anyonecanconnect"                  , "anyone-can-connect"                ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-anyonecanconnect",
                   "anyonecansend","Global permissions",
                   "Anyone can connect, i.e. a publicly readable blockchain."},
    { "anyonecansend"                     , "anyone-can-send"                   ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-anyonecansend",
                   "anyonecanreceive","",
                   "Anyone can send, i.e. transaction signing not restricted by address."},
    { "anyonecanreceive"                  , "anyone-can-receive"                ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-anyonecanreceive",
                   "anyonecanreceiveempty","",
                   "Anyone can receive, i.e. transaction outputs not restricted by address."},
    { "anyonecanreceiveempty"                  , "anyone-can-receive-empty"                ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         1,          0,         0, 0.0, 10007, 0, "-FC-anyonecanreceiveempty",
                   "anyonecancreate","",
                   "Anyone can receive empty output, i.e. without permission grants, asset transfers and zero native currency."},
    { "anyonecancreate"                  , "anyone-can-create"                ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10006, 0, "-FC-anyonecancreate",
                   "anyonecanissue","",
                   "Anyone can create new streams."},
    { "anyonecanissue"                    , "anyone-can-issue"                  ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-anyonecanissue",
                   "anyonecanmine","",
                   "Anyone can issue new native assets."},
    { "anyonecanmine"                     , "anyone-can-mine"                   ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-anyonecanmine",
                   "anyonecanactivate","",
                   "Anyone can mine blocks (confirm transactions)."},
    { "anyonecanactivate"                 , "anyone-can-activate"                   ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10003, 0, "-FC-anyonecanactivate",
                   "anyonecanadmin","",
                   "Anyone can grant or revoke connect, send and receive permissions."},
    { "anyonecanadmin"                     , "anyone-can-admin"                   ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-anyonecanadmin",
                   "supportminerprecheck","",
                   "Anyone can grant or revoke all permissions."},
    { "supportminerprecheck"                         , "support-miner-precheck"                         ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         1,          0,         0, 0.0, 10007, 0, "-FC-supportminerprecheck",
                   "allowp2shoutputs","",
                   "Require special metadata output with cached scriptPubKey for input, to support advanced miner checks."},
    { "allowp2shoutputs"                         , "allow-p2sh-outputs"                         ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         1,          0,         0, 0.0, 10001, 0, "-FC-allowp2shoutputs",
                   "allowmultisigoutputs","",
                   "Allow pay-to-scripthash (P2SH) scripts, often used for multisig."},
    { "allowmultisigoutputs"                     , "allow-multisig-outputs"                     , 
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         1,          0,         0, 0.0, 10001, 0, "-FC-allowmultisigoutputs",
                   "setupfirstblocks","",
                   "Allow bare multisignature scripts, rarely used but still supported."},
                   
    { "setupfirstblocks"                       , "setup-first-blocks"                       , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,         60,         1,  31536000, 0.0, 10001, 0, "-FC-setupfirstblocks",
                   "miningdiversity","Consensus requirements",
                   "Length of initial setup phase in blocks, in which mining-diversity,\nadmin-consensus-* and mining-requires-peers are not applied."},    
    { "miningdiversity"                   , "mining-diversity"                   , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,    300000,          0,   1000000, 0.0, 10001, 0, "-FC-miningdiversity",
                   "adminconsensusupgrade","",
                   "Miners must wait <mining-diversity>*<active miners> between blocks."},
    { "adminconsensusupgrade"               , "admin-consensus-upgrade"               , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,    500000,          0,   1000000, 0.0, 10008, 0, "-FC-adminconsensusupgrade",
                   "adminconsensusadmin","",
                   "<admin-consensus-upgrade>*<active admins> needed to upgrade the chain."},
    { "adminconsensusadmin"               , "admin-consensus-admin"               , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,    500000,          0,   1000000, 0.0, 10001, 0, "-FC-adminconsensusadmin",
                   "adminconsensusactivate","",
                   "<admin-consensus-admin>*<active admins> needed to change admin perms."},
    { "adminconsensusactivate"                , "admin-consensus-activate"              , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,    500000,          0,   1000000, 0.0, 10003, 0, "-FC-adminconsensusactivate",            
                   "adminconsensusmine","",
                   "<admin-consensus-activate>*<active admins> to change activate perms."},
    { "adminconsensusmine"                , "admin-consensus-mine"              , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,    500000,          0,   1000000, 0.0, 10001, 0, "-FC-adminconsensusmine",            
                   "adminconsensuscreate","",
                   "<admin-consensus-mine>*<active admins> to change mining permissions."},
    { "adminconsensuscreate"                , "admin-consensus-create"              , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,         0,          0,   1000000, 0.0, 10006, 0, "-FC-adminconsensuscreate",            
                   "adminconsensusissue","",
                   "<admin-consensus-issue>*<active admins> to change create permissions."},
    { "adminconsensusissue"                , "admin-consensus-issue"              , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL , -1,         0,          0,   1000000, 0.0, 10003, 0, "-FC-adminconsensusissue",            
                   "lockadminminerounds","",
                   "<admin-consensus-issue>*<active admins> to change issue permissions."},
    { "lockadminminerounds"                       , "lock-admin-mine-rounds"                       , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_NOHASH  , -1,         10,         0,     10000, 0.0, 10007, 0, "-FC-setupfirstblocks",
                   "miningrequirespeers","Defaults for node runtime parameters",
                   "Ignore forks that reverse changes in admin or mine permissions after this many mining rounds have passed. Integer only."},    
    { "miningrequirespeers"               , "mining-requires-peers"             ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_NOHASH  , -1,         1,          0,         0, 0.0, 10001, 0, "-FC-miningrequirespeers",
                   "mineemptyrounds","",
                   "Nodes only mine blocks if connected to other nodes (ignored if only one permitted miner)."},                   
    { "mineemptyrounds"                   , "mine-empty-rounds"             ,
                   FC_PRM_INT32   | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL | FC_PRM_NOHASH, -1,  10000000,    -1000000,  1000000000, 0.0, 10007, 0, "-FC-mineemptyrounds",
                   "miningturnover","",
                   "Mine this many rounds of empty blocks before pausing to wait for new transactions. If negative, continue indefinitely (ignored if target-adjust-freq>0). Non-integer allowed."},                   
    { "miningturnover"                    , "mining-turnover"             ,
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE | FC_PRM_DECIMAL | FC_PRM_NOHASH, -1,    500000,          0,   1000000, 0.0, 10007, 0, "-FC-miningturnover",
                   "initialblockreward","",
                   "Prefer pure round robin between a subset of active miners to minimize forks (0.0) or random equal participation for all permitted miners (1.0)."},                   
/*                   
    { "minimumblocktxs"                   , "minimum-block-txs"             ,
                   FC_PRM_UINT32 | FC_PRM_USER | FC_PRM_CLONE  | FC_PRM_NOHASH  , -1,          0,          0,     1000, 0.0, 10007, 0, "-FC-minimumblocktxs",
                   "initialblockreward","",
                   "Recommended minimal number of transactions in block."},
*/                   
    { "firstblockreward"                 , "first-block-reward"             ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,        -1,         -1,1000000000000000000, 0.0, 10002, 0, "-FC-genesisblockreward",
                   "rewardhalvinginterval","",
                   "Different mining reward for first block only, ignored if negative."},
    { "initialblockreward"                 , "initial-block-reward"             ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,1000000000000000000, 0.0, 10001, 0, "-FC-initialblockreward",
                   "firstblockreward","Native blockchain currency (likely not required)",
                   "Initial block mining reward in raw native currency units."},
    { "rewardhalvinginterval"            , "reward-halving-interval"          ,
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,  52560000,         60,4294967295U, 0.0, 10001, 0, "-FC-rewardhalvinginterval",
                   "rewardspendabledelay","",
                   "Interval for halving of mining rewards, in blocks."},
    { "rewardspendabledelay"                  , "reward-spendable-delay"                  , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                , -1,          1,          1,    100000, 0.0, 10001, 0, "-FC-rewardspendabledelay",
                   "minimumperoutput","",
                   "Delay before mining reward can be spent, in blocks."},
    { "minimumperoutput"                     , "minimum-per-output"                     , 
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,         -1,1000000000, 0.0, 10001, 0, "-FC-minimumperoutput",
                   "maximumperoutput","",
                   "Minimum native currency per output (anti-dust), in raw units.\nIf set to -1, this is calculated from minimum-relay-fee."},
    { "maximumperoutput"                     , "maximum-per-output"                     , 
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,         100000000000000,         0,1000000000000000000, 0.0, 10001, 0, "-FC-maximumperoutput",
                   "minimumrelayfee","",
                   "Maximum native currency per output, in raw units."},
    { "minimumrelayfee"                     , "minimum-relay-fee"                     ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,1000000000, 0.0, 10001, 0, "-FC-minimumrelayfee",
                   "nativecurrencymultiple","",
                   "Minimum transaction fee, in raw units of native currency."},
    { "nativecurrencymultiple"            , "native-currency-multiple"                     ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,         100000000,          0,1000000000, 0.0, 10001, 0, "-FC-nativecurrencymultiple",
                   "skippowcheck","",
                   "Number of raw units of native currency per display unit."},
                   
                   
    { "skippowcheck"              , "skip-pow-check"              ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-skippowcheck",
                   "powminimumbits","Advanced mining parameters",
                   "Skip checking whether block hashes demonstrate proof of work."},
    { "powminimumbits"                      , "pow-minimum-bits"                    ,
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,         8,          1,        32, 0.0, 10001, 0, "-FC-powminimumbits",
                   "targetadjustfreq","",
                   "Initial and minimum proof of work difficulty, in leading zero bits."},
    { "targetadjustfreq"                    , "target-adjust-freq"                  , 
                   FC_PRM_INT32  | FC_PRM_USER | FC_PRM_CLONE                   , -1,        -1,         -1,4294967295U, 0.0, 10001, 0, "-FC-targetadjustfreq",
                   "allowmindifficultyblocks","",
                   "Interval between proof of work difficulty adjustments, in seconds, if negative - never adjusted."},
    { "allowmindifficultyblocks"          , "allow-min-difficulty-blocks"       ,
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         0,          0,         0, 0.0, 10001, 0, "-FC-allowmindifficultyblocks",
                   "onlyacceptstdtxs","",
                   "Allow lower difficulty blocks if none after 2*<target-block-time>."},
                                      
    { "onlyacceptstdtxs"                   , "only-accept-std-txs"                  , 
                   FC_PRM_BOOLEAN | FC_PRM_USER | FC_PRM_CLONE                  , -1,         1,          0,         0, 0.0, 10001, 0, "-FC-onlyacceptstdtxs",
                   "maxstdtxsize","Standard transaction definitions",
                   "Only accept and relay transactions which qualify as 'standard'."},
    { "maxstdtxsize"                 , "max-std-tx-size"                 , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,   4194304,       1024,  100000000, 0.0, 10001, 0, "-FC-maxstdtxsize",
                   "maxstdopreturnscount","",
                   "Maximum size of standard transactions, in bytes."},
    { "maxstdopreturnscount"                  , "max-std-op-returns-count"                  , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,        10,          0,      1024, 0.0, 10006, 0, "-FC-maxstdopreturnscount",
                   "maxstdopreturnsize","",
                   "Maximum number of OP_RETURN metadata outputs in standard transactions."},                   
    { "maxstdopreturnsize"                  , "max-std-op-return-size"                  , 
                   FC_PRM_UINT32  | FC_PRM_USER | FC_PRM_CLONE                  , -1,   2097152,          0,   67108864, 0.0, 10001, 0, "-FC-maxstdopreturnsize",
                   "maxstdopdropscount","",
                   "Maximum size of OP_RETURN metadata in standard transactions, in bytes."},                   
    { "maxstdopdropscount"                        , "max-std-op-drops-count"                        ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,         5,          0,       100, 0.0, 10001, 0, "-FC-maxstdopdropscount",
                   "maxstdelementsize","",
                   "Maximum number of OP_DROPs per output in standard transactions."},
    { "maxstdelementsize"                    , "max-std-element-size"                    ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,      8192,        128,     32768, 0.0, 10003, 0, "-FC-maxscriptelementsize",
                   "maxstdopdropsize","",
                   "Maximum size of data elements in standard transactions, in bytes."},
 
    { "maxstdopdropsize"                    , "max-std-op-drop-size"                    ,
                   FC_PRM_INT64   | FC_PRM_USER | FC_PRM_CLONE                  , -1,        64,          0,     32768, 0.0, 10001, 10003, "-FC-maxstdopdropsize",
                   "chainname","",
                   "Obsolete. Maximum size of OP_DROP metadata in standard transactions, in bytes."},
                   
    { "chainname"                              , "chain-name"                              ,
                   FC_PRM_STRING  | FC_PRM_GENERATED | FC_PRM_MINIMAL           , FC_PRM_NETWORK_NAME_MAX_SIZE,         0,          0,         0, 0.0, 10001, 0, "",
                   "protocolversion","",
                   "Chain name, used as first argument for floatchaind and floatchain-cli."},                   
    { "protocolversion"                   , "protocol-version"                  ,
                   FC_PRM_UINT32  | FC_PRM_GENERATED                            , -1,         0,          0,         0, 0.0, 10001, 0, "",
                   "networkmessagestart","",
                   "Protocol version at the moment of blockchain genesis."},
    { "networkmessagestart"                      , "network-message-start"                      ,
                   FC_PRM_BINARY  | FC_PRM_GENERATED  | FC_PRM_MINIMAL          ,  4,         0,          0,         0, 0.0, 10001, 0, "",
                   "addresspubkeyhashversion","",
                   "Magic value sent as the first 4 bytes of every peer-to-peer message."},
    { "addresspubkeyhashversion"                    , "address-pubkeyhash-version"                    ,
                   FC_PRM_BINARY  | FC_PRM_GENERATED | FC_PRM_MINIMAL           ,  4,         0,          0,         0, 0.0, 10001, 0, "",
                   "addressscripthashversion","",
                   "Version bytes used for pay-to-pubkeyhash addresses."},
    { "addressscripthashversion"              , "address-scripthash-version"              ,
                   FC_PRM_BINARY  | FC_PRM_GENERATED                             ,  4,         0,          0,         0, 0.0, 10001, 0, "",
                   "privatekeyversion","",
                   "Version bytes used for pay-to-scripthash addresses."},
    { "privatekeyversion"              , "private-key-version"              ,
                   FC_PRM_BINARY  | FC_PRM_GENERATED                             ,  4,         0,          0,         0, 0.0, 10001, 0, "",
                   "addresschecksumvalue","",
                   "Version bytes used for exporting private keys."},
    { "addresschecksumvalue"              , "address-checksum-value"              ,
                   FC_PRM_BINARY  | FC_PRM_GENERATED | FC_PRM_MINIMAL            ,  4,         0,          0,         0, 0.0, 10001, 0, "",
                   "genesispubkey","",
                   "Bytes used for XOR in address checksum calculation."},

                   
    { "genesispubkey"                     , "genesis-pubkey"                     ,
                   FC_PRM_BINARY  | FC_PRM_CALCULATED                           , 65,         0,          0,         0, 0.0, 10001, 0, "",
                   "genesisversion","",
                   "Genesis block coinbase output public key."},
    { "genesisversion"                    , "genesis-version"                    ,
                   FC_PRM_UINT32  | FC_PRM_CALCULATED                           , -1,         1,          0,        -1, 0.0, 10001, 0, "",
                   "genesistimestamp","",
                   "Genesis block version."},
    { "genesistimestamp"                   , "genesis-timestamp"                   ,
                   FC_PRM_UINT32  | FC_PRM_CALCULATED                           , -1,         0,          0,         0, 0.0, 10001, 0, "",
                   "genesisnbits","",
                   "Genesis block timestamp."},
    { "genesisnbits"                      , "genesis-nbits"                      ,
                   FC_PRM_UINT32  | FC_PRM_CALCULATED                           , -1,         0,          0,         0, 0.0, 10001, 0, "",
                   "genesisnonce","",
                   "Genesis block difficulty (nBits)."},
    { "genesisnonce"                      , "genesis-nonce"                      ,
                   FC_PRM_UINT32   | FC_PRM_CALCULATED                          , -1,         0,          0,         0, 0.0, 10001, 0, "",
                   "genesispubkeyhash","",
                   "Genesis block nonce."},
    { "genesispubkeyhash"                 , "genesis-pubkey-hash"                 ,
                   FC_PRM_BINARY  | FC_PRM_CALCULATED                           , 20,         0,          0,         0, 0.0, 10001, 0, "",
                   "genesisopreturnscript","",
                   "Genesis block coinbase output public key hash."},
    { "genesisopreturnscript"             , "genesis-op-return-script"             ,
                   FC_PRM_BINARY  | FC_PRM_CALCULATED                           ,300,         0,          0,         0, 0.0, 10001, 10006, "",
                   "genesishash","",
                   "Genesis block coinbase OP_RETURN script."},
    { "genesishash"                       , "genesis-hash"                       ,
                   FC_PRM_BINARY  | FC_PRM_CALCULATED                           , 32,         0,          0,         0, 0.0, 10001, 0, "",
                   "chainparamshash","",
                   "Genesis block hash."},
                    
                    
    { "chainparamshash"                      , "chain-params-hash"                      ,
                   FC_PRM_BINARY  | FC_PRM_CALCULATED | FC_PRM_NOHASH           , 32,         0,          0,         0, 0.0, 10001, 0, "",
                   "","",
                   "Hash of blockchain parameters, to prevent accidental changes."},
};


#endif  /* FLOATCHAINPARAMLIST_H */

